# Generated by Django 2.0.7 on 2018-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
