# Generated by Django 2.0.7 on 2018-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
