# Generated by Django 2.0.7 on 2018-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180912_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
