# Generated by Django 2.0.7 on 2018-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='rang',
            field=models.TextField(default='Непросвещённый'),
        ),
        migrations.AddField(
            model_name='user1',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
