# Generated by Django 2.0.7 on 2018-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181113_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rang',
            field=models.TextField(default='Непросвещённый'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
